myApp/instituto/alumnos/urls.py
from django.urls import path # type: ignore

from .import views


urlpatterns =[
    path('index',views.index,name='index'),
    path('base',views.base,name='base'),
    path('alumnos/deportes/', views.deportes, name='deportes'),
    path('nacional/', views.nacional, name='nacional'),
    path('noticiaInternacional',views.noticiaInternacional,name='noticiaInternacional'),
    path('registro',views.registro,name='registro'),
    path('usuarios_add',views.usuarios_add,name='usuarios_add'),
    path('usuarios_del/<str:pk>', views.usuarios_del, name='usuarios_del'),
    path('usuarios_findEdit/<int:pk>/', views.usuarios_findEdit, name='usuarios_findEdit'),
    path('usuarios_edit',views.usuarios_edit,name='usuarios_edit'),
    path('usuarios_list',views.usuarios_list,name='usuarios_list'),
    path('usuarioAdd',views.usuarioAdd,name='usuarioAdd'),
    path('usuarios_update',views.usuarios_update,name='usuarios_update'),
    path('usuarios/', views.usuarios_list, name='usuarios_list'),
    path('agregar-noticia/', views.agregar_noticia, name='agregar_noticia'),
    path('validar_nombre_usuario/', views.validar_nombre_usuario, name='validar_nombre_usuario'),
    path('agregar-imagen/<int:noticia_id>/', views.agregar_imagen, name='agregar_imagen'),
    path('eliminar_imagen/<int:foto_id>/', views.eliminar_imagen, name='eliminar_imagen'),
    path('modificar/<int:noticia_id>/', views.modificar_noticia, name='modificar_noticia'),
    path('guardar_modificacion/<int:noticia_id>/', views.guardar_modificacion, name='guardar_modificacion'),
    path('noticia/<int:noticia_id>/', views.detalle_noticia, name='detalle_noticia'),
    path('perfil/', views.perfil, name='perfil'),
    path('eliminar-noticia/<int:noticia_id>/', views.eliminar_noticia, name='eliminar_noticia'),
    path('aprobar_noticias/', views.aprobar_noticias, name='aprobar_noticias'),
    path('cambiar_estado/<int:noticia_id>/', views.cambiar_estado_noticia, name='cambiar_estado_noticia'),
    path('suscripciones/', views.suscripciones, name='suscripciones'),
    path('agregar_al_carrito/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('realizar-compra/', views.realizar_compra, name='realizar_compra'),  
    path('buscar_noticias/', views.buscar_noticias, name='buscar_noticias'),
    path('noticia/<int:noticia_id>/', views.detalle_noticia, name='detalle_noticia'),
    path('api/regiones/', views.regiones_por_comuna, name='api_regiones'),
    path('logout_view', views.logout_view, name='logout_view'),
    
 


    
    
]

myApp/instituto/instituto/urls.py
from django.contrib import admin
from django.urls import path, include
from alumnos import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('alumnos/', include('alumnos.urls')),
    path('no-autorizado/', views.no_autorizado, name='no_autorizado'),
    path('accounts/', include('django.contrib.auth.urls')),  # Configurar las URLs de autenticación de Django
    path('agregar-noticia/', views.agregar_noticia, name='agregar_noticia'),


    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myApp/instituto/alumnos/models.py
from django.db import models # type: ignore
from django.contrib.auth.models import User # type: ignore

# Create your models here. 
class Profesion(models.Model):
    id_profesion = models.AutoField(db_column='id_profesion', primary_key=True)
    profesion = models.CharField(max_length=20, blank=False, null=False)

    def __str__(self):
        return str(self.profesion)

class Region(models.Model):
    cod_region = models.IntegerField(primary_key=True)
    nombre_region = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre_region

class Comuna(models.Model):
    cod_comuna = models.IntegerField(primary_key=True)
    nombre_comuna = models.CharField(max_length=30)
    region = models.ForeignKey(Region, on_delete=models.CASCADE, related_name='comunas')

    def __str__(self):
        return self.nombre_comuna

class Usuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profesion = models.ForeignKey(Profesion, on_delete=models.SET_NULL, null=True, blank=True)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True, blank=True)
    comuna = models.ForeignKey(Comuna, on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return self.user.username

class Tipo_usuario(models.Model):
    id_tipo_usuario = models.IntegerField(primary_key=True)
    descripcion =models.CharField(max_length=400, blank=False, null=False)

    def __str__(self):
        return str(self.id_tipo_usuario)
    
class Categoria(models.Model):
    id = models.AutoField(primary_key=True)  # Campo autoincremental para el ID
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre
    
class EstadoNoticia(models.Model):
    id_estado = models.AutoField(primary_key=True)
    descripcion= models.TextField()

    def __str__(self):
        return self.descripcion
class Noticia(models.Model):
    titulo = models.CharField(max_length=200)
    historia = models.TextField()
    historia2 = models.TextField()
    textoAgregado = models.TextField()
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_publicacion = models.DateField()
    ubicacion = models.CharField(max_length=100)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    estado = models.ForeignKey(EstadoNoticia, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.titulo
    
class Foto(models.Model):
    imagen = models.ImageField(upload_to='fotos_noticias')
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE, related_name='fotos')  # Relaciona con `Noticia`

    def __str__(self):
        return f'Foto de la Noticia: {self.noticia.titulo}'
    
class Producto(models.Model):
    id_producto = models.AutoField(primary_key=True)
    nombre_producto = models.TextField()
    valor_producto =  models.IntegerField()
    descripcion = models.TextField()
    cantidad = models.IntegerField()
    tiempo_mes = models.IntegerField()
    def __str__(self):
        return self.nombre_producto

class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    productos = models.ManyToManyField('Producto', through='ItemCarrito')

    def __str__(self):
        return f"Carrito de {self.usuario.username}"
    def total_carrito(self):
        items = self.itemcarrito_set.all()
        total = sum(item.producto.valor_producto * item.cantidad for item in items)
        return total

class ItemCarrito(models.Model):
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.cantidad} x {self.producto.nombre_producto}'

myApp/instituto/alumnos/views.py
from django.contrib.auth.decorators import login_required, user_passes_test # type: ignore
from django.shortcuts import render,redirect ,get_object_or_404 # type: ignore
from .models import Usuario, Profesion, Categoria, Region, Comuna, Noticia, Foto, EstadoNoticia, Producto, Carrito, ItemCarrito
from django.contrib.auth.models import User # type: ignore
from django.views.decorators.http import require_POST, require_GET # type: ignore
from django.http import JsonResponse, HttpResponse # type: ignore
from .forms import FotoForm, NoticiaForm
from django.contrib import messages # type: ignore
from django.contrib.auth import logout, authenticate, login   # type: ignore
from django.db.models import Q

def logout_view(request):
    logout(request)
    # Redirigir a una página o URL después del logout
    return redirect('index')

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('perfil')
        else:
            mensaje = "Nombre de usuario o contraseña incorrectos."
            return render(request, 'registration/login.html', {'mensaje': mensaje})
    return render(request, 'registration/login.html')

@require_POST
def usuarioAdd(request):
    nom_usuario = request.POST.get('nom_usuario')
    correo = request.POST.get('correo')
    password = request.POST.get('pass')
    password2 = request.POST.get('pass2')
    profesion_id = request.POST.get('profesion')
    comuna_name = request.POST.get('ciudad')

    # Validación rápida (puedes agregar validaciones más detalladas según sea necesario)
    if not (nom_usuario and correo and password and password2 and profesion_id and comuna_name):
        mensaje = "Todos los campos son requeridos."
        return render(request, 'alumnos/registro.html', {'mensaje': mensaje})

    if password != password2:
        mensaje = "Las contraseñas no coinciden."
        return render(request, 'alumnos/registro.html', {'mensaje': mensaje})

    try:
        # Crear un nuevo usuario de Django
        nuevo_usuario = User.objects.create_user(username=nom_usuario, email=correo, password=password)

        # Obtener la instancia de Comuna
        try:
            comuna = Comuna.objects.get(nombre_comuna=comuna_name)
        except Comuna.DoesNotExist:
            mensaje = "La comuna seleccionada no es válida."
            return render(request, 'alumnos/registro.html', {'mensaje': mensaje})

        # Crear un usuario extendido asociado
        usuario_extendido = Usuario(
            user=nuevo_usuario,
            profesion_id=profesion_id,
            comuna=comuna,  # Asignar la instancia de Comuna
        )
        usuario_extendido.save()

        mensaje = "Usuario registrado correctamente."
        return redirect('perfil')  # Redirigir a la página de perfil o la que desees

    except Exception as e:
        mensaje = f"Error al registrar usuario: {str(e)}"
        return render(request, 'alumnos/registro.html', {'mensaje': mensaje})


def buscar_noticias(request):
    query = request.GET.get('q')
    print("Query recibida:", query)

    # Filtrar las noticias que coincidan con la búsqueda
    resultados = Noticia.objects.filter(
        Q(titulo__icontains=query) |
        Q(autor__username__icontains=query)  # Filtrar por nombre de usuario del autor
    ).distinct()

    # Preparar los resultados para mostrar en la plantilla
    context = {
        'resultados': resultados,
        'query': query,
    }

    return render(request, 'alumnos/detalle_noticia.html', context)


def detalle_noticia(request, noticia_id):
    # Obtener la instancia de la noticia usando el ID
    noticia = get_object_or_404(Noticia, id=noticia_id)

    # Puedes obtener las imágenes asociadas a la noticia
    imagenes = noticia.fotos.all()  # Suponiendo que 'fotos' es el nombre relacionado con las imágenes

    context = {
        'noticia': noticia,
        'imagenes': imagenes,
    }
    return render(request, 'alumnos/detalle_noticia.html', context)

def validar_datos_formulario(nombres, apellidos, nom_usuario, telefono, email, password):
    # Validar cada campo según las reglas establecidas
    if not (3 <= len(nombres) <= 20):
        return False
    if not (3 <= len(apellidos) <= 20):
        return False
    if not (4 <= len(nom_usuario) <= 15):
        return False
    if not (len(telefono) == 9):
        return False
    if not (len(password) >= 8):
        return False
    if not (email.endswith('@gmail.com') or email.endswith('@hotmail.com') or email.endswith('@hotmail.es') or email.endswith('@yahoo.es') or email.endswith('@duocuc.cl')):
        return False
    # Añadir más validaciones según sea necesario
    return True

def validar_nombre_usuario(request):
    nom_usuario = request.GET.get('nom_usuario', None)
    existe = User.objects.filter(username=nom_usuario).exists()
    return JsonResponse({'existe': existe})

def es_staff(user):
    return user.is_authenticated and user.is_staff

def no_autorizado(request):
    return render(request, 'alumnos/no_autorizado.html')

def nacional(request):
    categoria_nacional = Categoria.objects.get(id=1)
    estado_publicada = EstadoNoticia.objects.get(id_estado=5)  # Ajusta el ID según tu configuración en la base de datos
    noticias = Noticia.objects.filter(categoria=categoria_nacional, estado=estado_publicada)
    return render(request, 'alumnos/nacional.html', {'noticias': noticias})

def noticiaInternacional(request):
    categoria_internacional = Categoria.objects.get(id=2)
    estado_publicada = EstadoNoticia.objects.get(id_estado=5)  # Ajusta el ID según tu configuración en la base de datos

    # Filtrar las noticias por categoría internacional y estado aprobada
    noticias = Noticia.objects.filter(categoria=categoria_internacional, estado=estado_publicada)

    return render(request, 'alumnos/noticiaInternacional.html', {'noticias': noticias})

def deportes(request):
    categoria_deportes = Categoria.objects.get(id=3)
    estado_publicada = EstadoNoticia.objects.get(id_estado=5)  # Ajusta el ID según tu configuración en la base de datos
    noticias = Noticia.objects.filter(categoria=categoria_deportes, estado=estado_publicada)
    return render(request, 'alumnos/deportes.html', {'noticias': noticias})

def usuarios_add(request):
    profesiones = Profesion.objects.all()
    context = {'profesiones': profesiones}
    return render(request,'alumnos/usuarios_add.html',context)

def registro(request):
    profesiones = Profesion.objects.all()
    comunas = Comuna.objects.all()

    if request.method == 'POST':
        nom_usuario = request.POST.get('nom_usuario')
        correo = request.POST.get('correo')
        password = request.POST.get('pass')
        pass2 = request.POST.get('pass2')
        profesion_id = request.POST.get('profesion')
        comuna_id = request.POST.get('ciudad')

        # Verificar que las contraseñas coincidan
        if password != pass2:
            # Aquí podrías manejar un mensaje de error o redirigir a una página de error
            return HttpResponse("Las contraseñas no coinciden.")

        try:
            # Crear un nuevo usuario básico
            user = User.objects.create_user(username=nom_usuario, email=correo, password=password)

            # Crear o actualizar el perfil de Usuario asociado
            usuario, created = Usuario.objects.get_or_create(user=user)

            # Asignar la profesión al usuario
            if profesion_id:
                profesion = Profesion.objects.get(id_profesion=profesion_id)
                usuario.profesion = profesion
                usuario.save()

            # Asignar la comuna al usuario
            if comuna_id:
                comuna = Comuna.objects.get(id=comuna_id)
                usuario.comuna = comuna
                usuario.save()

            return redirect('perfil')  # Redirigir a la página de perfil o donde desees

        except Exception as e:
            # Manejar cualquier error que pueda ocurrir durante la creación del usuario
            mensaje = f"Error al registrar usuario: {str(e)}"
            context = {
                'profesiones': profesiones,
                'comunas': comunas,
                'mensaje': mensaje,
            }
            return render(request, 'alumnos/registro.html', context)

    context = {
        'profesiones': profesiones,
        'comunas': comunas,
    }
    return render(request, 'alumnos/registro.html', context)


def regiones_por_comuna(request):
    comuna_id = request.GET.get('comuna_id')
    regiones = Region.objects.filter(comunas__id=comuna_id).distinct().values('id', 'nombre_region')

    return JsonResponse(list(regiones), safe=False)

def base(request):
    context={}
    return render(request,'alumnos/base.html',context)

def index(request):
    # Obtener la categoría de deportes y el estado 'Publicada'
    categoria_deportes = Categoria.objects.get(nombre='Deportes')
    estado_publicada = EstadoNoticia.objects.get(id_estado=5)  # Ajusta el ID según tu configuración en la base de datos
    noticias_carousel = Noticia.objects.filter(estado=estado_publicada)[:3]
    # Filtrar las noticias de deportes por categoría y estado
    noticias_deportes = Noticia.objects.filter(categoria=categoria_deportes, estado=estado_publicada)[:1]
    
    # Obtener otras noticias para mostrar en el carousel y en la columna de noticias internacionales
    noticias_internacional = Noticia.objects.filter(categoria__nombre='Internacional', estado=estado_publicada)[:1]

    context = {
        'noticias_deportes': noticias_deportes,
        'noticias_internacional': noticias_internacional,
        'noticias_carousel': noticias_carousel,
    }

    return render(request, 'alumnos/index.html', context)

@login_required

myApp/instituto/alumnos/templates/alumnos/agregar-noticia.html
<!-- templates/alumnos/agregar_noticia.html -->

{% extends "alumnos/base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'recursosCss/styleSheet.css' %}">
<div class="container">
    <h1>Agregar Noticia</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="titulo">Título:</label>
            <input type="text" class="form-control" id="titulo" name="titulo" required>
        </div>
        <div class="form-group">
            <label for="historia">Parrafo 1:</label>
            <textarea class="form-control" id="historia" name="historia" required></textarea>
        </div>

        <div class="form-group">
            <label for="historia2">Parrafo 2:</label>
            <textarea class="form-control" id="historia2" name="historia2" required></textarea>
        </div>

        <div class="form-group">
            <label for="textoAgregado">Texto Adicional:</label>
            <textarea class="form-control" id="textoAgregado" name="textoAgregado" required></textarea>
        </div>

        <input type="hidden" id="autor" name="autor" value="{{ request.user.username }}">
        <div class="form-group">
            <label for="fecha_publicacion">Fecha de Publicación:</label>
            <input type="date" class="form-control" id="fecha_publicacion" name="fecha_publicacion" readonly>
        </div>
        <div class="form-group">
            <label for="ubicacion">Ubicación:</label>
            <input type="text" class="form-control" id="ubicacion" name="ubicacion" required>
        </div>

        <div class="form-group">
            <label for="categoria">Categoría:</label>
            <select class="form-control" id="categoria" name="categoria" required>
                {% for categoria in categorias %}
                <option value="{{ categoria.id }}">{{ categoria.nombre }}</option>
                {% endfor %}
            </select>
        </div>

        <!-- Campo oculto para el estado -->
        <input type="hidden" id="estado" name="estado" value="Ingresada">

        <button type="submit" class="btn btn-primary">Agregar Noticia</button>
    </form>
</div>

<script>
    // Establecer la fecha actual como valor por defecto en el campo de fecha
    document.addEventListener('DOMContentLoaded', (event) => {
        const today = new Date();
        const yyyy = today.getFullYear();
        const mm = String(today.getMonth() + 1).padStart(2, '0'); // Enero es 0
        const dd = String(today.getDate()).padStart(2, '0');
        const formattedDate = `${yyyy}-${mm}-${dd}`;

        document.getElementById('fecha_publicacion').value = formattedDate;
    });
</script>

{% endblock %}

myApp/instituto/alumnos/templates/alumnos/aprobar_noticias.html
{% extends "alumnos/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'recursosCss/styleSheet.css' %}">
<h1>Noticias Ingresadas</h1>
<table class="table">
    <thead>
        <tr>
            <th>Título</th>
            <th>Estado</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for noticia in noticias %}
        <tr>
            <td>{{ noticia.titulo }}</td>
            <td>{{ noticia.estado }}</td>
            <td>
                <div class="btn-group" role="group" aria-label="Acciones">
                    <form action="{% url 'cambiar_estado_noticia' noticia.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="estado_id" value="2">
                        <button type="submit" class="btn btn-success">Aprobar</button>
                    </form>
                    <form action="{% url 'cambiar_estado_noticia' noticia.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="estado_id" value="3">
                        <button type="submit" class="btn btn-danger">Rechazar</button>
                    </form>
                    <form action="{% url 'cambiar_estado_noticia' noticia.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="estado_id" value="4">
                        <button type="submit" class="btn btn-warning">Modificar</button>
                    </form>

                    <form action="{% url 'cambiar_estado_noticia' noticia.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="estado_id" value="5">
                        <button type="submit" class="btn btn-success">Publicada</button>
                    </form>
                    <form style="display: inline;">
                        <button type="button" class="btn btn-warning" data-toggle="modal"
                            data-target="#modalDetalles{{ noticia.id }}">
                            Detalles
                        </button>
                    </form>

                    <form style="display: inline;">
                        <button type="button" class="btn btn-primary" data-toggle="modal"
                            data-target="#modalImagenes{{ noticia.id }}">Imágenes
                        </button>
                    </form>

                    <!-- Modal para Ver Imágenes de la Noticia -->
                    <div class="modal fade" id="modalImagenes{{ noticia.id }}" tabindex="-1" role="dialog"
                        aria-labelledby="modalImagenesLabel{{ noticia.id }}" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modalImagenesLabel{{ noticia.id }}">Imágenes de la
                                        Noticia</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    {% for foto in noticia.fotos.all %}
                                    <img src="{{ foto.imagen.url }}" alt="Imagen" class="img-thumbnail">
                                    {% empty %}
                                    <p>No hay imágenes disponibles para esta noticia.</p>
                                    {% endfor %}
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Modal para Detalles de la Noticia -->
                    <div class="modal fade" id="modalDetalles{{ noticia.id }}" tabindex="-1" role="dialog"
                        aria-labelledby="modalDetallesLabel{{ noticia.id }}" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modalDetallesLabel{{ noticia.id }}">Detalles de la
                                        Noticia</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p><strong>Autor:</strong> --{{ noticia.autor }}--</p>
                                    <p><strong>Título:</strong> {{ noticia.titulo }}</p>
                                    <p><strong>Fecha de Publicación:</strong> {{ noticia.fecha_publicacion }}</p>
                                    <p><strong>Estado:</strong> {{ noticia.estado }}</p>
                                    <p><strong>Contenido:</strong></p>
                                    <p>{{ noticia.historia }}</p>
                                    <p>{{ noticia.historia2 }}</p>
                                    <p>{{ noticia.textoAgregado }}</p>
                                    <p><strong>Ubicación:</strong> {{ noticia.ubicacion }}</p>
                                    <p><strong>Categoría:</strong> {{ noticia.categoria }}</p>
                                    <!-- Otros detalles que desees mostrar -->
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                </div>
                            </div>
                        </div>
                    </div>



                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock %}

myApp/instituto/alumnos/templates/alumnos/base2.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    holad desde base 2
    <li class"nav-item dropdown>
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown4">
            
        </a>
        <div class="dropdown-menu"></div>

    </li>
    
</body>
</html>

myApp/instituto/alumnos/templates/alumnos/contacto.html
<!-- instituto/alumnos/templates/alumnos/contacto.html -->
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario de Contacto</title>
    {% bootstrap_css %}
</head>
<body>
    <div class="container mt-5">
        <h1>Formulario de Contacto</h1>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>
    {% bootstrap_javascript %}
</body>
</html>

myApp/instituto/alumnos/templates/alumnos/form_contacto.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario de Contacto</title>
    <a class="nav-link active" aria-current="page" href="{% url 'formulario_contacto' %}" id="aTransition" style="text-decoration:none; color: #1b1b1b;">Contacto</a>

    {% bootstrap_css %}
</head>
<body>
    <div class="container mt-5">
        <h1>Formulario de Contacto</h1>
        <form method="POST" action="{% url 'enviar_contacto' %}">
            {% csrf_token %}
            <div class="mb-3">
                <label for="nombre" class="form-label">Nombre:</label>
                <input type="text" id="nombre" name="nombre" class="form-control" required>
            </div>

            <div class="mb-3">
                <label for="email" class="form-label">Correo electrónico:</label>
                <input type="email" id="email" name="email" class="form-control" required>
            </div>

            <div class="mb-3">
                <label for="mensaje" class="form-label">Mensaje:</label>
                <textarea id="mensaje" name="mensaje" rows="4" class="form-control" required></textarea>
            </div>

            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>
    {% bootstrap_javascript %}
</body>
</html>

myApp/instituto/alumnos/templates/alumnos/usuarios_edit.html
{% extends "alumnos/base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'recursosCss/editarUsuario.css' %}">

<div style="text-align: center; font-size: 1.5rem; font-weight: 600;">
{% if request.user.is_authenticated %}
<p>Bienvenido, {{ request.user.username }}</p>
{% endif %}
</div>

{% if mensaje %}
<div class="alert alert-danger">{{ mensaje }}</div>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_username">Nombre de usuario:</label>
        <input type="text" id="id_username" name="username" value="{{ user.username }}" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="id_email">Correo electrónico:</label>
        <input type="email" id="id_email" name="email" value="{{ user.email }}" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="id_profesion">Profesión:</label>
        <select id="id_profesion" name="profesion" class="form-control">
            {% for profesion in profesiones %}
            <option value="{{ profesion.id }}" {% if profesion.id == usuario.profesion.id %} selected {% endif %}>{{ profesion.profesion }}</option>
            {% endfor %}
        </select>
    </div>
    
    
    
    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
</form>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#id_region').change(function () {
            var region_id = $(this).val();
            if (region_id) {
                $.ajax({
                    url: '/obtener_comunas/',  // URL de la vista para obtener comunas
                    type: 'GET',
                    data: {
                        'region_id': region_id
                    },
                    success: function (data) {
                        $('#id_comuna').html(data);
                    }
                });
            } else {
                $('#id_comuna').html('<option value="">Seleccionar comuna</option>');
            }
        });
    });
</script>

{% endblock %}